### PR TITLE
Added period

### PR DESCRIPTION
**Pull request by bvssvni**

### CODE REVIEW

**Comment by indiv0** [comment]
Do we need to open PRs for minor changes like this?

**Comment by bvssvni** [comment]
Can you could merge multiple times using the same PR?

**Comment by indiv0** [comment]
@bvssvni I'm not sure. I was just thinking that something like this could be done with a direct edit.

:+1: for the merge.

Also, regarding PRs, what's the policy? Just 1 person needs to review or how should we do this?

**Comment by bvssvni** [comment]
@Indiv0 Direct edit would be good for such small changes.

1 person to review is what we do 90% of the time, so I think it is good for blog posts too.

**Comment by indiv0** [comment]
Alright.

I'll merge this PR then.

**Pull request merged**
