### PR TITLE
Blog post: Breaking Changes

### PR DESCRIPTION
**Pull request by bvssvni**

### CODE REVIEW

**Comment by indiv0** [comment]
Post looks good!

I'm OK with this PR being merged once the Travis CI build passes.

Also I've realized I haven't opened an issue on how to locally build and view the blog. I'll make an issue for that.

**Comment by bvssvni** [comment]
I just copied from the introductory post and edited directly on Github. Still, it would be nice to have instructions for viewing it locally.

**Comment by indiv0** [comment]
@bvssvni https://github.com/PistonDevelopers/blog.piston.rs/issues/25 :)

**Comment by indiv0** [comment]
Merging.

**Comment by indiv0** [comment]
@bvssvni also whoops I just noticed you're missing a period after "input".

**Comment by bvssvni** [comment]
@Indiv0 https://github.com/PistonDevelopers/blog.piston.rs/pull/26

**Pull request merged**
